# Generated by Django 5.0 on 2025-09-25 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='GKSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('date', models.DateField()),
                ('note', models.TextField(blank=True)),
                ('review_note', models.TextField(blank=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sheets', to='core.project')),
            ],
            options={
                'ordering': ['-date', 'project'],
            },
        ),
        migrations.CreateModel(
            name='BoQItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('unit_of_measure', models.CharField(max_length=20)),
                ('contracted_quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boq_items', to='core.project')),
            ],
            options={
                'ordering': ['project', 'code'],
                'unique_together': {('project', 'code')},
            },
        ),
        migrations.CreateModel(
            name='ReviewToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255, unique=True)),
                ('token_type', models.CharField(choices=[('approve', 'Approve'), ('reject', 'Reject')], max_length=7)),
                ('expires_at', models.DateTimeField()),
                ('used', models.BooleanField(default=False)),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_tokens', to='core.gksheet')),
            ],
            options={
                'ordering': ['-expires_at'],
            },
        ),
        migrations.CreateModel(
            name='GKEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('comment', models.TextField(blank=True)),
                ('boq_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='core.boqitem')),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='core.gksheet')),
            ],
            options={
                'unique_together': {('sheet', 'boq_item')},
            },
        ),
    ]
