# Generated by Django 5.0 on 2025-09-27 22:26

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BoQItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('uom', models.CharField(max_length=20)),
                ('contract_qty', models.DecimalField(decimal_places=3, default=0, max_digits=16)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('close_note', models.TextField(blank=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boq_items', to='core.project')),
            ],
        ),
        migrations.CreateModel(
            name='GKSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq_no', models.PositiveIntegerField()),
                ('period_from', models.DateField(blank=True, null=True)),
                ('period_to', models.DateField(blank=True, null=True)),
                ('qty_this_period', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=16)),
                ('qty_cumulative', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=16)),
                ('note', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('locked', 'Locked')], default='draft', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('boq_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gk_sheets', to='core.boqitem')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_gk_sheets', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gk_sheets', to='core.project')),
            ],
            options={
                'ordering': ['boq_item__code', 'seq_no'],
                'indexes': [models.Index(fields=['project', 'boq_item', 'seq_no'], name='core_gkshee_project_947270_idx'), models.Index(fields=['status'], name='core_gkshee_status_6a7c6b_idx')],
                'unique_together': {('boq_item', 'seq_no')},
            },
        ),
        migrations.AddIndex(
            model_name='boqitem',
            index=models.Index(fields=['project', 'code'], name='core_boqite_project_77e54e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='boqitem',
            unique_together={('project', 'code')},
        ),
    ]
