# Generated by Django 5.0 on 2025-09-28 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoQCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=255)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boq_categories', to='core.project')),
            ],
            options={
                'ordering': ('sequence', 'name'),
            },
        ),
        migrations.AddField(
            model_name='boqitem',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='core.boqcategory'),
        ),
        migrations.AddIndex(
            model_name='boqitem',
            index=models.Index(fields=['project', 'category', 'code'], name='core_boqite_project_2ba0aa_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='boqcategory',
            unique_together={('project', 'sequence')},
        ),
    ]
