# Generated by Django 5.0 on 2025-09-29 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_boqcategory_boqitem_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='boq_currency',
            field=models.CharField(default='EUR', max_length=3),
        ),
    ]
