# Generated by Django 5.0 on 2025-09-30 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_project_boq_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boqitem',
            name='closed_at',
        ),
    ]
