# Generated by Django 5.0 on 2025-10-01 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_boqitem_closed_at'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='boqitem',
            unique_together={('project', 'code', 'category')},
        ),
    ]
