# Generated by Django 5.0 on 2025-10-01 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_boqitem_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gksheet',
            old_name='note',
            new_name='opis_izvedenih_radova',
        ),
    ]
