# Generated by Django 5.0 on 2025-10-02 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_note_gksheet_opis_izvedenih_radova'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boqitem',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
