# Generated by Django 5.0 on 2025-10-02 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_boqitem_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boqitem',
            name='title',
            field=models.TextField(),
        ),
    ]
